name: Build and Push Docker Images

# 触发条件：可以根据需要修改，这里设置为推送到main分支时触发
on:
  push:
    branches: [ main ]
  # 也可以添加手动触发选项
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保能获取完整的commit历史

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          debug: true  # 启用调试输出

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        env:
          DOCKER_DEBUG: true  # 启用Docker调试输出

      - name: Extract metadata for tagging
        id: meta
        run: |
          # 获取当前日期（格式：YYYYMMDD）
          echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          # 获取7位commit ID
          echo "COMMIT_SHORT=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
          # 显示获取的信息用于调试
          echo "Date tag: $(date +'%Y%m%d')"
          echo "Commit short: $(git rev-parse --short=7 HEAD)"

      - name: Build and push RockyLinux9 Toolbox image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./toolbox/rockylinux9/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/rockylinux9_toolbox:${{ steps.meta.outputs.DATE_TAG }}-${{ steps.meta.outputs.COMMIT_SHORT }}
            ${{ secrets.DOCKER_USERNAME }}/rockylinux9_toolbox:latest
          # 启用详细日志
          build-args: |
            DEBUG=true
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.meta.outputs.DATE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # 显示构建过程详细信息
          debug: true

      - name: Build and push Ubuntu2204 Toolbox image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./toolbox/ubuntu2204/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ubuntu2204_toolbox:${{ steps.meta.outputs.DATE_TAG }}-${{ steps.meta.outputs.COMMIT_SHORT }}
            ${{ secrets.DOCKER_USERNAME }}/ubuntu2204_toolbox:latest
          # 启用详细日志
          build-args: |
            DEBUG=true
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.meta.outputs.DATE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # 显示构建过程详细信息
          debug: true

      - name: Verify pushed images
        if: success()
        run: |
          echo "Successfully pushed the following images:"
          echo "${{ secrets.DOCKER_USERNAME }}/rockylinux9_toolbox:${{ steps.meta.outputs.DATE_TAG }}-${{ steps.meta.outputs.COMMIT_SHORT }}"
          echo "${{ secrets.DOCKER_USERNAME }}/ubuntu2204_toolbox:${{ steps.meta.outputs.DATE_TAG }}-${{ steps.meta.outputs.COMMIT_SHORT }}"
          echo "Also tagged as 'latest'"
